export const EXPORT_SLIDE_COMPONENT_LISTS = [
  { id: "overall-slide", title: "Overall" },
  { id: "overall-slide-2", title: "Overall 2" },
  { id: "overall-slide-3", title: "Overall 3" },
  { id: "overall-slide-4", title: "Overall 4" },
  // { id: "title-component", title: "Title" },
  // { id: "overall-component", title: "Overall" },
  // { id: "facebook-section-component", title: "Facebook" },
  // { id: "facebook-awareness-01-component", title: "Facebook Awareness (1/2)" },
  // { id: "facebook-awareness-02-component", title: "Facebook Awareness (2/2)" },
  // { id: "facebook-reach-01-component", title: "Facebook Reach (1/2)" },
  // { id: "facebook-reach-02-component", title: "Facebook Reach (2/2)" },
  // {
  //   id: "facebook-engagement-01-component",
  //   title: "Facebook Engagement (1/2)",
  // },
  // {
  //   id: "facebook-engagement-02-component",
  //   title: "Facebook Engagement (2/2)",
  // },
  // { id: "facebook-traffic-01-component", title: "Facebook Traffic (1/2)" },
  // { id: "facebook-traffic-02-component", title: "Facebook Traffic (2/2)" },
  // { id: "facebook-video-01-component", title: "Facebook Video (1/2)" },
  // { id: "facebook-video-02-component", title: "Facebook Video (2/2)" },
  // { id: "facebook-message-01-component", title: "Facebook Message (1/2)" },
  // { id: "facebook-message-02-component", title: "Facebook Message (2/2)" },
  // { id: "facebook-lead-01-component", title: "Facebook Lead (1/2)" },
  // { id: "facebook-lead-02-component", title: "Facebook Lead (2/2)" },
  // {
  //   id: "facebook-conversion-01-component",
  //   title: "Facebook Conversion (1/2)",
  // },
  // {
  //   id: "facebook-conversion-02-component",
  //   title: "Facebook Conversion (2/2)",
  // },
  // { id: "facebook-catalog-01-component", title: "Facebook Catalog (1/2)" },
  // { id: "facebook-catalog-02-component", title: "Facebook Catalog (2/2)" },
  // { id: "google-section-component", title: "Google" },
  // { id: "sem-conversion-component", title: "SEM Conversion" },
  // { id: "sem-click-component", title: "SEM Click" },
  // { id: "gdn-component", title: "GDN" },
  // { id: "discovery-component", title: "Discovery" },
  // { id: "youtube-component", title: "Youtube" },
  // { id: "tiktok-section-component", title: "Tiktok" },
  // { id: "tiktok-reach-01-component", title: "Tiktok Reach" },
  // { id: "tiktok-video-01-component", title: "Tiktok Video" },
  // { id: "tiktok-traffic-01-component", title: "Tiktok Traffic" },
  // { id: "tiktok-lead-01-component", title: "Tiktok Lead" },
  // { id: "tiktok-conversion-01-component", title: "Tiktok Conversion" },
  // { id: "line-section-component", title: "Line" },
  // { id: "line-reach-01-component", title: "Line Reach" },
  // { id: "line-gain-friends-01-component", title: "Line Gain Friends" },
  // { id: "taboola-section-component", title: "Taboola" },
  // { id: "taboola-component", title: "Taboola" },
  // { id: "end-slide-component", title: "End" },
];
