export const SALE_CONFIG = {
  thresold: 5.0,
  keywords: {
    // Direct sales actions (high weight)
    ออเดอร์: 3,
    สั่ง: 3,
    order: 3,
    ซื้อ: 3,
    จอง: 3,
    เปิดรับ: 3,
    สั่งมา: 3,
    สั่งได้: 3,
    ติดต่อ: 2,

    // Price/discount terms (high weight)
    ลดราคา: 4,
    ลด: 2,
    โปรโมชั่น: 3,
    พิเศษ: 2,
    ฟรี: 3,
    แถม: 3,
    ส่วนลด: 3,

    // Shipping/delivery (medium weight)
    ส่งฟรี: 3,
    จัดส่ง: 2,
    ค่าส่ง: 2,
    ส่งถึงบ้าน: 2,
    delivery: 2,
    ship: 2,

    // Urgency/scarcity (medium weight)
    จำกัด: 2,
    ด่วน: 2,
    รีบ: 2,
    เหลือ: 2,
    ของแถม: 2,
    พร้อมส่ง: 2,

    // Contact/inquiry (low-medium weight)
    สนใจ: 1,
    ทัก: 1,
    DM: 2,
    inbox: 2,
    สอบถาม: 1,
    Line: 1,

    // Product listing indicators (NEW - high weight)
    พิกัด: 3,
    ลิงค์: 2,
    link: 2,

    // Commercial indicators
    ราคา: 1,
    บาท: 1,
    มีของแถม: 2,
    ครบ: 1,
    บิล: 1,
  },

  contactPatterns: ["line:", "dm", "inbox", "ทัก", "สอบถาม"],

  urgencyWords: ["ด่วน", "รีบ", "จำกัด", "เหลือ", "limited"],

  // emojiPattern: /[✨🤟❤️🔥💥⭐🎉🛒💰🎁]/g,

  salesHashtagPatterns: [
    /ตลาดนัด/i,
    /พรีออเดอร์/i,
    /นำเข้า/i,
    /ส่งฟรี/i,
    /preorder/i,
  ],
};

export const SENTIMENT_CONFIG = {
  positiveKeywords: [
    // Original positive keywords
    "ดี",
    "สวย",
    "น่ารัก",
    "ดีใจ",
    "สุดยอด",
    "ยอดเยี่ยม",
    "ชอบ",
    "รัก",
    "เยี่ยม",
    "มีประสิทธิภาพ",
    "ฟิน",
    "happy",
    "best",
    "good",
    "ใส",
    "สดใส",
    "แนะนำ",
    "ปลอดภัย",
    "ได้ผล",
    "ฟื้นฟู",
    "บรรเทา",
    "ช่วย",
    "สุขภาพดี",
    "ล้ำลึก",
    "มีคุณภาพ",
    "เจ๋ง",
    "วิเศษ",
    "ดีงาม",
    "โอเค",
    "ราคาดี",
    "คุ้ม",
    "โปร",
    "seller",
    "#1",

    // New positive keywords from dataset analysis
    "เห็นผลชัด",
    "ลงทุนน้อย",
    "นุ่ม",
    "สะอาด",
    "ต้องลอง",
    "ปิ๊ง",
    "เก่ง",
    "หวาน",
    "งาม",
    "สว่าง",
    "ออร่า",
    "คนงาม",
    "ยิ้ม",
    "cute",
    "สนุก",
    "เท่",
    "cool",
    "wow",
    "amazing",
    "perfect",
    "love",
    "like",
    "super",
    "great",
    "excellent",
    "wonderful",
    "fantastic",
    "awesome",
    "brilliant",
    "outstanding",
    "impressive",
    "remarkable",
    "beautiful",
    "gorgeous",
    "stunning",
    "lovely",
    "adorable",
    "sweet",
    "nice",
    "pleasant",
    "enjoyable",
    "delightful",
    "charming",
    "attractive",
    "appealing",
    "interesting",
    "exciting",
    "thrilling",
    "entertaining",
    "amusing",
    "fun",
    "funny",
    "hilarious",
    "cheerful",
    "joyful",
    "glad",
    "pleased",
    "satisfied",
    "content",
    "grateful",
    "thankful",
    "appreciative",
    "impressed",
    "amazed",
    "surprised",
    "delighted",
    "excited",
    "enthusiastic",
    "passionate",
    "eager",
    "hopeful",
    "optimistic",
    "confident",
    "proud",
    "successful",
    "effective",
    "efficient",
    "beneficial",
    "helpful",
    "useful",
    "valuable",
    "worthwhile",
    "meaningful",
    "significant",
    "important",
    "reliable",
    "trustworthy",
    "quality",
    "premium",
    "superior",
    "excellent",
    "ideal",
    "comfortable",
    "convenient",
    "easy",
    "simple",
    "smooth",
    "quick",
    "fast",
  ],

  negativeKeywords: [
    // Original negative keywords
    "แย่",
    "เลว",
    "ไม่ดี",
    "ไม่ชอบ",
    "เกลียด",
    "ผิดหวัง",
    "แพง",
    "ไม่คุ้ม",
    "ระคายเคือง",
    "แสบ",
    "เจ็บ",
    "ปวด",
    "อักเสบ",
    "บอบบาง",
    "ปัญหา",
    "เสียใจ",
    "โกรธ",
    "หงุดหงิด",
    "เบื่อ",
    "เครียด",
    "ไม่ได้ผล",
    "ไม่เหมาะ",
    "เสียหาย",
    "อันตราย",
    "ผลข้างเคียง",
    "ไม่ปลอดภัย",

    // New negative keywords from dataset analysis
    "เหนื่อย",
    "หนีตาย",
    "ใจสั่น",
    "อารมณ์แรง",
    "ตุน",
    "มัดมือชก",
    "ตกหล่น",
    "ไม่มีการประกาศ",
    "คาดหวัง",
    "ไม่เข้าใจ",
    "แย่งซีน",
    "ผลุด",
    "bad",
    "terrible",
    "awful",
    "horrible",
    "disgusting",
    "annoying",
    "frustrating",
    "irritating",
    "disappointing",
    "unsatisfactory",
    "unacceptable",
    "inappropriate",
    "wrong",
    "incorrect",
    "false",
    "fake",
    "misleading",
    "confusing",
    "unclear",
    "difficult",
    "hard",
    "complicated",
    "complex",
    "challenging",
    "tough",
    "rough",
    "harsh",
    "severe",
    "serious",
    "critical",
    "dangerous",
    "risky",
    "unsafe",
    "insecure",
    "unstable",
    "unreliable",
    "untrustworthy",
    "questionable",
    "doubtful",
    "suspicious",
    "concerning",
    "worrying",
    "alarming",
    "shocking",
    "disturbing",
    "upsetting",
    "distressing",
    "painful",
    "uncomfortable",
    "unpleasant",
    "awkward",
    "embarrassing",
    "shameful",
    "regrettable",
    "unfortunate",
    "unlucky",
    "unfair",
    "unjust",
    "biased",
    "offensive",
    "insulting",
    "rude",
    "impolite",
    "disrespectful",
    "inconsiderate",
    "selfish",
    "greedy",
    "dishonest",
    "deceitful",
    "corrupt",
    "evil",
    "wicked",
    "cruel",
    "mean",
    "nasty",
    "hostile",
    "aggressive",
    "violent",
    "destructive",
    "harmful",
    "toxic",
    "ugly",
    "unattractive",
  ],

  neutralKeywords: [
    // Original neutral keywords
    "ราคา",
    "ขนาด",
    "สี",
    "น้ำหนัก",
    "วิธีใช้",
    "ส่วนผสม",
    "ประกอบด้วย",
    "มี",
    "คือ",
    "เป็น",
    "จะ",
    "อาจ",
    "สามารถ",
    "ควร",
    "ขาย",
    "สั่ง",
    "dm",
    "line",
    "order",
    "ml",
    "บาท",
    "เวลา",
    "วัน",
    "ข้อมูล",

    // New neutral keywords from dataset analysis
    "กิจกรรม",
    "งาน",
    "โปส",
    "เปิด",
    "ปิด",
    "ตำแหน่ง",
    "routine",
    "cleanser",
    "moisturizer",
    "sunscreen",
    "serum",
    "spf",
    "pa",
    "contains",
    "ingredients",
    "formula",
    "texture",
    "application",
    "usage",
    "instructions",
    "directions",
    "steps",
    "process",
    "method",
    "technique",
    "approach",
    "system",
    "procedure",
    "protocol",
    "guideline",
    "recommendation",
    "suggestion",
    "advice",
    "tip",
    "information",
    "details",
    "specification",
    "description",
    "explanation",
    "definition",
    "meaning",
    "purpose",
    "function",
    "role",
    "responsibility",
    "task",
    "job",
    "work",
    "activity",
    "action",
    "behavior",
    "performance",
    "operation",
    "structure",
    "organization",
    "arrangement",
    "composition",
    "configuration",
    "setup",
    "installation",
    "preparation",
    "planning",
    "design",
    "development",
    "creation",
    "production",
    "manufacturing",
    "assembly",
    "construction",
    "building",
    "establishment",
    "foundation",
    "basis",
    "principle",
    "concept",
    "idea",
    "theory",
    "hypothesis",
    "assumption",
    "belief",
    "opinion",
    "view",
    "perspective",
    "position",
    "strategy",
    "plan",
    "program",
    "project",
    "campaign",
    "effort",
    "test",
    "trial",
    "study",
    "research",
    "analysis",
    "examination",
    "review",
    "evaluation",
    "assessment",
    "measurement",
    "calculation",
    "estimation",
    "prediction",
    "forecast",
    "expectation",
    "requirement",
    "demand",
    "request",
    "question",
    "issue",
    "matter",
    "subject",
    "topic",
    "category",
    "type",
    "kind",
    "variety",
    "version",
    "model",
    "brand",
    "product",
    "item",
    "object",
    "element",
    "component",
    "part",
    "section",
    "portion",
    "percentage",
    "ratio",
    "rate",
    "level",
    "degree",
    "amount",
    "quantity",
    "number",
    "total",
    "average",
    "range",
    "limit",
    "space",
    "area",
    "location",
    "place",
    "position",
    "address",
    "direction",
    "method",
    "tool",
    "device",
    "equipment",
    "machine",
    "system",
    "network",
    "platform",
    "service",
    "facility",
    "resource",
    "material",
    "substance",
    "solution",
    "date",
    "time",
    "schedule",
    "calendar",
  ],

  positiveEmojis: /[😊😍🥰❤️💕👍🌟⭐✅🧸🪁🪀🩵]/g,
  negativeEmojis: /[😭😞😔💔😩😤😠😡🤬]/g,

  salesIndicators: [
    "ส่งฟรี",
    "ลด",
    "โปร",
    "พิเศษ",
    "limited",
    "สั่งได้",
    "มาแล้ว",
    "bestseller",
    "เปิดรับออเดอร์",
    "กดสั่ง",
    "ซื้อครบ",
    "free shipping",
    "discount",
    "sale",
    "offer",
    "deal",
    "promotion",
    "special",
    "exclusive",
    "limited time",
    "limited edition",
    "new arrival",
    "hot item",
    "popular",
    "trending",
    "must have",
    "recommended",
    "top rated",
    "customer favorite",
  ],

  // Additional patterns specific to Thai social media
  complaintIndicators: [
    "ผิดหวัง",
    "ไม่เข้าใจ",
    "ควรแก้ไข",
    "ข้อมูลตกหล่น",
    "ไม่มีการประกาศ",
    "มัดมือชก",
    "ไม่ยุติธรรม",
    "คาดหวัง",
    "บอกตรงๆ",
  ],

  excitementIndicators: [
    "เอ้อออออ",
    "หนู๊ว",
    "ยัยแสบ",
    "จิ๋วแสบ",
    "555",
    "5555",
    "55555",
  ],
};
